### ISSUE TITLE
questions about implement and deploy details  

### ISSUE THREAD

**Issue by math-yyj** [wanghao9610/OV-DINO#10]
Nice work !
and I have two questions:
1. How many GPUs needed for full-training ?
2. Is there any guide for ONNX export ?

many thanks !

**Comment by wanghao9610** [comment]
Thanks for your attention to our work. 
(1) OV-DINO is pre-trained on 32 A100 GPUs with batch size 128, then finetuned on 8 A100 GPUs with batch size 32.
(2) Good suggestion, I will add it to the road map. I'm the only one coding, please stay tuned.

**Comment by math-yyj** [comment]
> Thanks for your attention to our work. (1) OV-DINO is pre-trained on 32 A100 GPUs with batch size 128, then finetuned on 8 A100 GPUs with batch size 32. (2) Good suggestion, I will add it to the road map. I'm the only one coding, please stay tuned.

Thank you for your kindly reply. 

And, how many hours did pretrain and finetune cost ?

**Comment by wanghao9610** [comment]
OV-DINO<sup>1</sup> pre-trained on O365 takes about 1 day, OV-DINO<sup>2</sup> pre-trained on (O365, GoldG) takes about 3 days, and OV-DINO<sup>3</sup> pre-trained on (O365, GoldG, CC1M‡) takes about 1 week, the fine-tuninging on COCO takes about 0.5 day. Note: The above training costs are not accurate exactly, just provided for clarification.
