### ISSUE TITLE
微调时的训练过程图

### ISSUE THREAD

**Issue by Zwh195** [wanghao9610/OV-DINO#13]
您好，想请问一下在coco数据集上微调时，有没有支持查看训练过程的参数（tensorboard类似的）？

**Comment by wanghao9610** [comment]
默认是支持tensorboard的。你可以查看一下你的训练输出路径中是否有 events.out.tfevents.* 的文件，如果有则说明已经有tensorboard的日志了。进入到训练输出路径中，执行以下命令：
```bash
tensorboard --logdir=./
```
在这之前，你可能需要先安装一下tensorboard。参考：pip install tensorboard 。

**Comment by Zwh195** [comment]
好的好的，谢谢您！
