### ISSUE TITLE
A short question regarding the version of Objects 365

### ISSUE THREAD

**Issue by kaijinz0228** [wanghao9610/OV-DINO#19]
Dear authors:
I notice that the pre-training code you shared recently includes a short instruction about downloading Objects365-v1. Just want to confirm that the following results are produced using Objects365-v1, rather than Objects365-v2, right?
![image](https://github.com/user-attachments/assets/17a59c74-7a30-47c0-85c4-f6a7d919280b)

Thank you

**Comment by wanghao9610** [comment]
Yes, the Objects365 is the v1 not the v2, it is the 609K images version.
