### ISSUE TITLE
关于微调

### ISSUE THREAD

**Issue by wpNZC** [wanghao9610/OV-DINO#20]
你好，仅仅像使用教程那样并不能对自定义数据集进行微调，相关issue我也没能理解明白，也自我尝试探索了一下，但并不能如愿实现，请问能出一个更为详细的有关自定义数据微调的教程或文档等等吗

**Comment by wanghao9610** [comment]
我看issue里面有小伙伴是可以正常进行训练和测试的，说明根据文档是可以正常进行自定义数据微调的。可以详细描述一下你的问题吗？
或许你可以参考一下coco 微调的过程，这个过程是确定的。自定义数据集的话，需要参考coco的格式进行。

**Comment by wpNZC** [comment]
我尝试自定义数据集，输入：
h scripts/finetune.sh   projects/ovdino/configs/ovdino_swin_tiny224_bert_base_ft_custom_24ep.py   ../inits/ovdino/ovdino_swint_ogc-coco50.2_lvismv40.1_lvis32.9.pth，报错了：AssertionError: Attribute 'thing_classes' in the metadata of 'custom_train_ovd_unipro' cannot be set to a different value!所以我猜想不能直接运行，需要进一步配置。
但是参考/OV-DINO/ovdino/detrex/data/datasets的coco_ovd和register_coco_ovd文件进行修改仍然没能实现微调，而后我发现/OV-DINO/ovdino/configs/common/data有额外的文件，解除了注释进行配置如下所示：
register_coco_ovd_instances(
    "cc",  # dataset_name
    {'person','box','carbon'},  # custom_data_info
    "/data1/vision/OV-DINO/OV-DINO/datas/custom/annotations/train.json",  # annotations_jsonfile
    "/data1/vision/OV-DINO/OV-DINO/datas/custom/train",  # image_root
    3,  # number_of_classes, default: 80
    "full",  # template, default: full
)
register_coco_ovd_instances(
    "custom_val_ovd_unipro",
    {'person','box','carbon'},
    "/data1/vision/OV-DINO/OV-DINO/datas/custom/annotations/val.json",
    "/data1/vision/OV-DINO/OV-DINO/datas/custom/val",
    3,
    "full",
)
register_coco_ovd_instances(
    "custom_test_ovd",
    {},
    "/path/to/test.json",
    "/path/to/test/images",
    3,
    "identity",
)
而在register_custom_ovd.py中修改如下：
_PREDEFINED_SPLITS = {
    # image_root, json_file, num_sampled_classes, template
    "custom_train_ovd_unipro": (
        "custom/train",
        "custom/annotations/train.json",
        3,
        "full",
    ),
    "custom_val_ovd_unipro": (
        "custom/val",
        "custom/annotations/val.json",
        3,
        "full",
    ),
    "custom_test_ovd": (
        "custom/test",
        "custom/annotations/test.json",
        3,
        "identity",
    ),
}
从此前的
AssertionError: Attribute 'thing_classes' in the metadata of 'custom_train_ovd_unipro' cannot be set to a different value!
变成了
File "/data1/vision/OV-DINO/OV-DINO/ovdino/detrex/data/datasets/coco_ovd.py", line 333, in register_coco_ovd_instances
    MetadataCatalog.get(name).set(
TypeError: detectron2.data.catalog.Metadata.set() argument after ** must be a mapping, not set
可我此时并没有修改coco_ovd.py并对照源码二次确认没有修改（此前修改过，但是改回了源码）。看起来他正确地读取识别到了我构建的类别，可是仍然需要对数据进一步进行处理？
我对Detectron2,detrex了解甚少，不太理解数据集的注册机制等等，恳请你能进一步提供帮助和指导以学习。感谢！

**Comment by wanghao9610** [comment]
这个报错是因为，你把同一个数据集注册了2次，而这2次的thing_classes不同导致的。
注释掉：https://github.com/wanghao9610/OV-DINO/blob/fdede96e147bd858cdd08ca65018cfbcdc98a1be/ovdino/detrex/data/datasets/__init__.py#L21，这样只会保留ovdino/configs/common/data/custom_ovd.py 中的注册。
你尝试一下？

**Comment by wanghao9610** [comment]
@wpNZC I have updated the custom dataset instruction guideline, please re-pull the repo. If you have any promblem, don't hesitate to let me know.

**Comment by wpNZC** [comment]
> 这个报错是因为，你把同一个数据集注册了2次，而这2次的thing_classes不同导致的。 注释掉：[L21](https://github.com/wanghao9610/OV-DINO/blob/fdede96e147bd858cdd08ca65018cfbcdc98a1be/ovdino/detrex/data/datasets/__init__.py#L21)，这样只会保留ovdino/configs/common/data/custom_ovd.py 中的注册。 你尝试一下？

根据新版本的注释与报错引导已经足以开始微调了，十分感谢！

不过再提一点点建议，或许你可以再丰富一下注释，有一些细节的改善可能可以让项目更容易上手并传播。例如"thing_dataset_id_to_contiguous_id"，我还以为是都改成0，但我需要修改为{1: 0, 2: 1, 3:2}，以及尽管你提到了具体需要修改的文件，但是好像/OV-DINO/ovdino/detrex/data/datasets/custom_ovd也同样需要修改，其中的lambda函数仍然为load_coco_json，不过报错说明了解决办法。

最后，再次感谢你的开源项目，我也乐意向他人推荐此项目。

**Comment by wanghao9610** [comment]
感谢你的建议和推荐，我已经根据你的建议修改了相关的代码，并提供了更多的注释。欢迎你在使用过程中提出更多的建议，帮助这个项目完善的更好～

**Comment by Mengxj521** [comment]
@wpNZC @wanghao9610 按照上面的步骤进行custom_ovd数据处理，微调时出现TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
![1724160419273](https://github.com/user-attachments/assets/2fa29864-5104-45f1-afed-7babd99f6344)
经过定位发现在./OV-DINO-main/ovdino/detrex/data/datasets/custom_ovd.py中，变量sampled_cat_names为多维嵌套列表，导致输入分词器格式错误我将这段代码摘出来后，我把列表展开可以正常进行分词，但是训练会报错，请教一下你们知道什么原因吗？ 感谢！！！
![1724160126859](https://github.com/user-attachments/assets/093fff1d-b6b8-4170-9017-b5fee93965a3)
![1724160605981](https://github.com/user-attachments/assets/639dd074-5396-44a8-9e72-3a7abfec8d5d)

**Comment by wanghao9610** [comment]
从你最后的RuntinmeError报错看，你的模型中的num_class参数没有修改，还是用的默认的coco的80个类别。在你的例子中，需要修改[ovdino_swin_tiny224_bert_base_ft_custom_24ep.py L37](https://github.com/wanghao9610/OV-DINO/blob/d2215529ad2ddda3717e476a7c0b9e4865bd8b83/ovdino/projects/ovdino/configs/ovdino_swin_tiny224_bert_base_ft_custom_24ep.py#L37)为:
```python
model.num_classes = 2
```

**Comment by Mengxj521** [comment]
修改后可以正常训练，不过我在bert.py中BERTEncoder对输入x做了这个操作 x= [item for sublist in x for item in sublist]，请问对训练精度有影响吗

**Comment by wanghao9610** [comment]
你这个操作是将子列表取出来，我之前的代码应该已经可以实现了，能跑通的话，应该是没有必要的。

**Comment by Mengxj521** [comment]
好的，可能我某个地方修改了没有还原，非常感谢！！！😀
