### ISSUE TITLE
训练很慢

### ISSUE THREAD

**Issue by zuoshaobo** [wanghao9610/OV-DINO#21]
finetune的时候，很慢，有办法提高速度吗？我是固定几个目标的检测，是不是text的特征可以预先生成好？

**Comment by wanghao9610** [comment]
训练慢主要是所有的模型权重都需要更新，你可以考虑在ovdino/projects/ovdino/configs/ovdino_swin_tiny224_bert_base_infer_demo.py L35下面添加下面的代码：
```python
model.language_backbone.is_freeze=True
```
固定住text encoder的特征。

**Comment by zuoshaobo** [comment]
好的，谢谢
