### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by lfreee** [wanghao9610/OV-DINO#27]
Can you provide a inferencr script? Thank you

**Comment by wanghao9610** [comment]
@lfreee Hello, I have provided the script, please refer to [Local inference Demo][https://github.com/wanghao9610/OV-DINO?tab=readme-ov-file#computer-demo](https://github.com/wanghao9610/OV-DINO?tab=readme-ov-file#computer-demo).

**Comment by lfreee** [comment]
Thank you, I provided the wrong location.
