### ISSUE TITLE
请问如何多卡训练？

### ISSUE THREAD

**Issue by FelixZhang7** [wanghao9610/OV-DINO#29]

**Comment by wanghao9610** [comment]
@FelixZhang7 Refer to [Fine-Tuning](https://github.com/wanghao9610/OV-DINO?tab=readme-ov-file#4-fine-tuning) and [Pre-training](https://github.com/wanghao9610/OV-DINO?tab=readme-ov-file#5-pre-training). For more detail, refer to the [finetune.sh](https://github.com/wanghao9610/OV-DINO/blob/main/ovdino/scripts/finetune.sh) and [pretrain.sh](https://github.com/wanghao9610/OV-DINO/blob/main/ovdino/scripts/pretrain.sh).
