### ISSUE TITLE
About the scalability of OV-DINO

### ISSUE THREAD

**Issue by kaijinz0228** [wanghao9610/OV-DINO#34]
Dear authors,

Have you conducted some experiments to evaluate the scalability of OV-DINO, like using objects365-v2 to train the model？The Grounding DINO-L model was trained using the v2 version. 

Thank you

**Comment by wanghao9610** [comment]
Hello, @kaijinz0228 , thank you for your interest in our work. We don't have enough computational resources to conduct more experiments, while it is almost certain that OV-DINO will obtain better results with more training data or a larger model size. We have established O365 pre-training code, you could pre-train it on the O365 v2 dataset.
