### ISSUE TITLE
Curiosity about how to solve different labels towards same objects among different dataset.

### ISSUE THREAD

**Issue by Cloud65000** [wanghao9610/OV-DINO#36]
I'm curious about one factor of pre-trained datasets. Are there any of the following in your pre-training dataset： The label descriptions of the same target object are different in different datasets.  For instance, COCO describes birds with the label "bird", but Obj365 describes birds with the label "wild bird". How do you solve this kind of problem in the pre-trained process?  During the inference process, if the model "eats" a picture with birds for example, how will it predict the object birds? Will the model predict it as "bird" or "wild bird"?

**Comment by wanghao9610** [comment]
In pre-training, we keep the name as the original. Actually, the ambiguity is not important for pre-training, different people may call the same thing with different names, while the two names are the same thing.

**Comment by Cloud65000** [comment]
I see. I guess we can keep the name as the original because BERT will help us generate similar embeddings for those different descriptions of the same object.
