### ISSUE TITLE
Ask for different size of the checkpoint

### ISSUE THREAD

**Issue by Cloud65000** [wanghao9610/OV-DINO#38]
Have you tried to pre-train the model using the image backbone larger than swint？Like swinb or swinl?

**Comment by wanghao9610** [comment]
We don't have much more computational resources to train the model. Even OV-DINO converges fast with only 24 epochs, while pre-training OV-DINO with Swin-L will take almost 32 A100 GPUs for two weeks, which is too expensive for us to afford.
