### ISSUE TITLE
infer with different category_names

### ISSUE THREAD

**Issue by robinjoe93** [wanghao9610/OV-DINO#39]
I want to use different category_names when infer multiple times, such as ["apple"] the first time and ["sofa", "table"] the second time. 
Must the model have to be reloaded between the first and second time?

**Comment by wanghao9610** [comment]
You should consider deploy the [web_inference demo](https://github.com/wanghao9610/OV-DINO?tab=readme-ov-file#computer-demo) or try our [online_demo](http://47.115.200.157:7860/).

**Comment by robinjoe93** [comment]
> You should consider deploy the [web_inference demo](https://github.com/wanghao9610/OV-DINO?tab=readme-ov-file#computer-demo) or try our [online_demo](http://47.115.200.157:7860/).

Thank you for your reply
