### ISSUE TITLE
Confused about differences between the process of demo(without SAM) and train

### ISSUE THREAD

**Issue by Cloud65000** [wanghao9610/OV-DINO#41]
I first ran the code of train_net.py and then the demo.py. When running the training process, there's a train dataloader that adds a template for each category. However, when I ran the demo according to the instructions in README.md(The text is input as "class1 class2" format), I saw the categories' names are together fed into the demo code and added template together like this "a photo of a cat dog.". Is there any wrong with the way I operate? If no, the templated text seems to be malophonic.
![image](https://github.com/user-attachments/assets/65bcb43a-4c93-4024-829c-480adff054ba)

**Comment by wanghao9610** [comment]
@Cloud65000 This process is right. Our training procedure adopts a unified prompt (shortened as unipro) pipeline, so the inference procedure should also adopt the unipro pipeline to maintain consistency with the training process. However, there are minor differences between training and inference. The training unipro samples one template from 80 templates referred to in CLIP, while the inference unipro takes all 80 templates and then averages them to obtain a better text embedding representation. You can find the details and explanation in our paper.

**Comment by Cloud65000** [comment]
> I will read the paper carefully later. I'm curious about how the model will detect two kinds of objects from the image. Since the model receives the templated text list containing 80 elements like "a photo of cat dog.", "a doodle of a cat dog." etc., how will it predict bboxes for cats and dogs respectively?

I'm curious about this because I see the BERT generates an embedding for each templated element in the list(sentence level).

**Comment by wanghao9610** [comment]
> I will read the paper carefully later. I'm curious about how the model will detect two kinds of objects from the image. Since the model receives the templated text list containing 80 elements like "a photo of cat dog.", "a doodle of a cat dog." etc., how will it predict bboxes for cats and dogs respectively?

You may misunderstand the unipro pipeline. To detect "cat" and "dog", the unified prompt will be like "a bright photo of a cat." and "a photo of a dog.", not "a doodle of a cat dog.", and there will be 80 prompted texts for each category when inferencing. You can print the prompted texts.

**Comment by wanghao9610** [comment]
In the [demo.py](https://github.com/wanghao9610/OV-DINO/blob/a43ebae38da332c4357e533bd6ed60efce0f0d7b/ovdino/demo/demo.py#L74), I utilized a space to concatenate the input category_names into a list. You can find the answer in the code.

**Comment by Cloud65000** [comment]
![image](https://github.com/user-attachments/assets/d602c6ab-1722-41e8-9bbc-099f08d81d27)
![image](https://github.com/user-attachments/assets/cd2617c9-ede5-4dc5-908a-7967739457c9)
Do you mean this part? But in README.md, for a single image with multiple categories, it is said to prompt the model as "class1 class2". The function "clean_words_or_phrase" together with "for" cannot transfer "cat dog" to ["cat", "dog"]

**Comment by wanghao9610** [comment]
The args.category_names is already a list not a string, you print it and you will find it ...

**Comment by Cloud65000** [comment]
Oh! I ran it in the debug format(demo.py) and the argument I sent is the same as that of I ran in the bash format
![image](https://github.com/user-attachments/assets/b8b2f12a-5329-4ce2-afc1-51e95e00a466)
![image](https://github.com/user-attachments/assets/d6286bf1-db81-49d2-b618-9dacc0d374d2)
The former one got a list format args.category_names and the latter one got a string format args.category_names.
