### ISSUE TITLE
how to store demo.py result

### ISSUE THREAD

**Issue by LiaoZihZrong** [wanghao9610/OV-DINO#43]
Dear auth,
now i can use demo.py and see the result image,
but i don't know how to store it's result ( JSON or txt)

many thanks,

**Comment by wanghao9610** [comment]
@LiaoZihZrong You may refer this line [code](https://github.com/wanghao9610/OV-DINO/blob/a43ebae38da332c4357e533bd6ed60efce0f0d7b/ovdino/demo/app.py#L170), then utilize the following code to store the json_results.
```python
import json
with open("your_output_filename.json", "w")as f:
       json.dump(json_results, f)
```
Simply, you can ask ChatGPT for help, it can offer more detailed advice.
