### ISSUE TITLE
How is the CC1M dataset used in the code?

### ISSUE THREAD

**Issue by yuzhengfa** [wanghao9610/OV-DINO#44]
A very nice job. I noticed that your paper mentioned CC1M data, and I would like to ask how this data is used because I couldn't find the relevant dataloader in the code We look forward to your reply.

**Comment by wanghao9610** [comment]
@yuzhengfa Thanks for your attention. The code, log and dataset detail for [pre-training on [Objects365, GoldG, CC1M‡]](https://github.com/wanghao9610/OV-DINO?tab=readme-ov-file#pre-training-on-objects365-goldg-cc1m-datasets) will be released after our paper been accepted, please stay tuned.
