### ISSUE TITLE
How to train on heterogeneous datasets？

### ISSUE THREAD

**Issue by wwf1995** [wanghao9610/OV-DINO#45]
Thank you for your amazing work, I have a question I hope we can discuss together.

If there are several target detection datasets labeled with different objects in similar scenes (e.g., one part labeled with cars, one part labeled with pedestrians), can we use such a heterogeneous dataset to train a model to predict an all-class detection result? According to the idea of language aware query selection and language aware decoder it should be possible to accomplish such a function.

Do you have any idea about this? If this idea is valid then it would be a meaningful thought in application.

**Comment by wanghao9610** [comment]
@wwf1995 Hello, it is possible to train a detection model on heterogeneous datasets, while you need to keep the semantics consistent for the same categories across different datasets (they don't need to be the whole same nouns but share same semantics, e.g. person in dataset1, while human in dataset2).

**Comment by wwf1995** [comment]
@wanghao9610 One concern I have is whether the negative samples generated during training will affect the detection of the different classes？For example, if an image has vehicles and pedestrians, but only the pedestrians are labeled and not the vehicles, will it affect the results of the model's vehicle detection box when used as training data?

**Comment by wanghao9610** [comment]
Actually, almost all datasets are not labeled sufficiently. In other words, there exists a lot of images that are not annotated for all instances defined in the categories. And in the training schedule, the negative samples are considered for labeld data if the annotation is right. So, I think the insufficient annotation will not affect the detection performance dramatically.
