### ISSUE TITLE
Memory Error When Training with Large Dataset (SIGKILL Error)

### ISSUE THREAD

**Issue by tinnel123666888** [wanghao9610/OV-DINO#53]
I encountered the following error while training with my custom dataset:

```
File "/home/users/ghc/OV-DINO/ovdino/./tools/train_net.py", line 329, in <module>
    launch(
  File "/home/users/ghc/OV-DINO/ovdino/detectron2-717ab9/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/users/ghc/anaconda3/envs/ovdino3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/users/ghc/anaconda3/envs/ovdino3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/users/ghc/anaconda3/envs/ovdino3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGKILL
```

It appears to be a memory issue, as I am training on a dataset of approximately 2 million images, and the memory usage goes up to 500GB. The issue arises when loading the dataset for training. However, the dataset loads without issues in other models I’ve tried.

I would like to know if there are any recommended solutions for better memory management or dataset loading strategies for such large datasets. I’ve considered options like:
- Loading the dataset in batches to reduce memory usage
- Using memory-mapped files to reduce the memory footprint

But I am unsure of the best approach in this case. Any advice or suggestions would be greatly appreciated!

Thanks in advance!

**Comment by wanghao9610** [comment]
Hello, tinnel @tinnel123666888 . The high memory consumption issue stems from detectron2, which builds the dataset_dicts for the entire dataset during data pre-processing, making it unsuitable for large dataset loading. In our training setup, we required almost 900GB of memory (for 2.4M images) to run the experiment, and I haven't yet built a solution to this problem as the experiment is running😅. I have considered some potential solutions:

> 1) Avoid loading all information during data pre-processing and pre-loading. In OV-DINO, the category_names/grounding_phrases/image_caption are stored as strings which consume a significant amount of memory. You can instead load these strings in the main forward function, which should theoretically save considerable memory.
> 2) Reduce the [dataloader.train.num_workers](https://github.com/wanghao9610/OV-DINO/blob/20073914cc10caa734d4336442cf198c12a72710/ovdino/projects/ovdino/configs/ovdino_swin_tiny224_bert_base_ft_custom_24ep.py#L54) to a smaller number, such as 4, which will also decrease memory consumption.

Hope it can help you.

**Comment by tinnel123666888** [comment]
Thank you very much for your helpful explanation regarding the high memory consumption issue. Your suggestions are very insightful and will certainly guide my next steps in addressing the problem.

I am from Tsinghua University, and I have sent an email with my contact details(xtr24@mails.tsinghua.edu.cn). Please kindly check it when you have a moment, as I would love to discuss this further and exchange ideas.
