### ISSUE TITLE
为什么没有支持windows的命令呢，这装起来太费劲了

### ISSUE THREAD

**Issue by wangjingyu001** [wanghao9610/OV-DINO#6]

**Comment by wanghao9610** [comment]
@wangjingyu001 Windows你可以试一下 WSL2，装一个Ubuntu的虚拟机，就可以在windows实现和Linux一样的指令了。

**Comment by wanghao9610** [comment]
你这种情况，尝试我们的在线[Demo](http://47.115.200.157:7860/)是一个更好的选择。
